language: java

jdk: openjdk8

install: true

services:
  - postgresql

before_script:
  - psql -c 'create database db_myerp;' -U postgres
 
script:
  - mvn clean install -P test-business, test-consumer










