language: java

jdk: openjdk8

services:
  - docker

before_install:
  - cd docker/dev
  - docker-compose up -d

script:
  - cd ../../src
  - mvn test -P test-consumer,test-business
  - cd ../docker/dev
  - docker-compose stop
  - docker-compose rm -v
  - docker-compose up






 













