language: java

jdk: openjdk8

services:
- postgresql

before_script:
- psql -c 'create database db_myerp;' -U postgres
- psql db_myerp < createDatabase.sql

script: 
- mvn clean install -P test-business,test-consumer


